language: node_js
cache:
  directories:
    - node_modules
    - -~/.npm
node_js: 
  - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  slack: espacio-de-estudio:Lt1swDIOAyUy8FANO4RM7HQh
  email:
    recipients:
    - julianandres.perez.30@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del proyeto"
  on:
    branch: master